# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fc7b19d3095b8d7af8850e482253a6496f008bae7902fe2a995dc7867e49be2a231ab2fe5f355bd3a8aa3615ce5d6b00451ed9cc35dbb8e0d27bb49876c99d6

test:
  secret_key_base: 1f5f95a41e40f43b25f8d06ca5f7c5ca90e08e1c0e65352010927206f8643bc9d85eab10dad8f5b41f409bc89995738d12536af46d11b223e3f8dea8525c8c9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
